### ISSUE TITLE
wrong spelling of ownerpass in the example mentioned which leads to the error.

### ISSUE THREAD

**Issue by prithvitewatia** [ashutoshvarma/pyxpdf#1]
Hi,
I think you are making a spelling mistake of ownerpass in the example you provide in the documentation. I think that should be ownerpass just like userpass and not ownerpss. This leads to error TypeError: pdftotext() got an unexpected keyword argument 'ownerpss'.

**Comment by ashutoshvarma** [comment]
Thanks for finding typo
