### ISSUE TITLE
Mac support?

### ISSUE THREAD

**Issue by trypsynth** [ashutoshvarma/pyxpdf#40]
Hi,
I love this library. It works well, and reads everything I could possibly want it to. However, when running
```shell
pip3.9 install pyxpdf
```
On mac, it throws an error. Is Mac support planned /easy to do? If not, can you recommend other libraries that are almost as good?
Thanks.

**Comment by afortiori** [comment]
I had the same issue on macOS 12.4, which was quickly resolved when I switched from python 3.9 to 3.8.
